config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets do
    member do
      get :star
    end
  end

  root "tweets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/star.rb
class Star < ApplicationRecord
  has_many :stars
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :stars

  validates :tweet, presence: true, length: {minimum: 1, maximum: 140}, allow_blank: false
  validates :link, presence: true
  validates :user_name, presence: true

  def star_count
    stars.count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except:[:index]

  # GET /tweets
  def index


    # Where takes one of things:
    #   - hash where the key is the name of the field, and the value is what to match EXACTLY
    #   - a small sql snippet that would normally appear in a WHERE clause if we were writing all the sql
    #
    # We want to get to a where clause like this: "tweet like %whatevs%"
    #
    # So build that string in the ruby activerecord `where`
    @tweets = Tweet.all.order("created_at DESC").where("tweet like ?", "%#{params[:search]}%")
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  def star
    @tweet = Tweet.find(params[:id])
    if @tweet.stars.count == 0
      @tweet.stars.create
      redirect_to @tweet, notice: 'Tweet was star-value was changed.'
    else
      @tweet.stars.delete_all
      redirect_to @tweet, notice: 'Tweet was star-value was changed.'
    end

  end

  private
    # Only allow a trusted parameter "white list" through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_name, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = MiniTwitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid.container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .pull-left
          %a.navbar-brand{:href => "/"}
            %i.fa.fa-twitter{"aria-hidden" => "true", style: 'margin-left: 10%; font-size: 25px; color: #79E7FF'}
          = link_to "/", class: "navbar-brand" do
            MiniTwitter
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to "Home", root_path
            %li
              = link_to new_tweet_path do
                New Tweet
          %ul.nav.navbar-nav.navbar-right
            %form.navbar-form.navbar-left
              .form-group
                %input.form-control.searchable-tweets{placeholder: "Search", type: "text"}/
              %button.btn.btn-default.searchable-button{type: "submit"} Submit

            - if user_signed_in?
              %li
                %p.navbar-text
                  = current_user.email
            %li
              - if user_signed_in?
                = link_to "LogOut", destroy_user_session_path, method: :delete
              - else
                = link_to "LogIn", new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/tweets/_form.html.haml
= form_for @tweet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @tweet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"

      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label "Tweet (140 char-max)", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :tweet, class: 'form-control'
  .form-group
    = f.label :user_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :user_name, class: 'form-control'
  .form-group
    = f.label :link, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :link, class: 'form-control'
  .form-group
  .pull-right
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/tweets/_tweet.html.haml
%tr
  %td
    = # index + 1
    \.
  %td
    %p
      = tweet.star_count
      = link_to star_tweet_path(tweet) do
        - if tweet.stars.count == 0
          %i.fa.fa-star-o{"aria-hidden" => "true"}
        - else
          %i.fa.fa-star{"aria-hidden" => "true"}
  %td
    %p
      = link_to tweet.tweet, tweet.link

      %em
        (
        = truncate(tweet.link, length: 25)
        )

  %td= link_to tweet.user_name
  %td= tweet.created_at

  %td
    = link_to tweet do
      %span.glyphicon.glyphicon-ok
  %td
    = link_to edit_tweet_path(tweet) do
      %span.glyphicon.glyphicon-pencil
  %td
    = link_to tweet, data: { confirm: 'Are you sure?' }, method: :delete do
      %span.glyphicon.glyphicon-remove

app/views/tweets/edit.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @tweet, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing tweet

= render 'form'

app/views/tweets/index.html.haml
.page-header
  %i.fa.fa-twitter{"aria-hidden" => "true", style: 'margin-left: 50%; font-size: 90px; color: #0000ff'}

  %h1 Listing tweets

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th #
        %th
          Favorite
          %i.fa.fa-star-o{"aria-hidden" => "true"}
          OR
          %i.fa.fa-star{"aria-hidden" => "true", style: 'color:#f0C300'}
        %th Tweet
        %th Poster
        %th Posted
        %th{:colspan => 3} Options

    %tbody.search-results
      = render @tweets

app/views/tweets/index.js.erb
$('.search-results').html('<%= j(render @tweets) %>')

app/views/tweets/new.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New tweet

= render 'form'

app/views/tweets/show.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_tweet_path(@tweet), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show tweet

%dl.dl-horizontal
  %dt Tweet(max char: 140):
  %dd= @tweet.tweet
  %dt User name:
  %dd= @tweet.user_name
  %dt Link:
  %dd= @tweet.link